import Foundation

/// Only factory images with one-time locale initialization may inherit the
/// Mac's language. Older images rewrote LANG on every boot.
enum GuestLocaleCatalog {
    static let capabilityToken = "tryomarchy.locale_support=2"
    static let koreanCapabilityToken = "tryomarchy.locale_support=3"

    static func supportsSelection(kernelCommandLine: String, requiresKorean: Bool = false) -> Bool {
        let tokens = kernelCommandLine.split(whereSeparator: { $0.isWhitespace })
        return tokens.contains(Substring(koreanCapabilityToken))
            || (!requiresKorean && tokens.contains(Substring(capabilityToken)))
    }

    /// Use the primary macOS language, not its region or a secondary preferred
    /// language. Only return locales generated by configure-rootfs.sh.
    static func initialLocale(preferredLanguages: [String], supportsKorean: Bool = false) -> String {
        let language = Locale.Language(identifier: preferredLanguages.first ?? "en")
        if language.languageCode?.identifier == "ko", supportsKorean { return "ko_KR.UTF-8" }
        guard language.languageCode?.identifier == "zh" else { return "en_US.UTF-8" }
        return language.script?.identifier == "Hant" ? "zh_TW.UTF-8" : "zh_CN.UTF-8"
    }
}

struct LanguageLaunchConfiguration: Equatable {
    static let environmentKey = "OMARCHY_QEMU_GPU_LOCALE"

    let environment: [String: String]

    static func make(
        baseEnvironment: [String: String],
        preferredLanguages: [String] = Locale.preferredLanguages,
        supportsSelection: Bool = true,
        supportsKorean: Bool = false
    ) -> Self {
        var environment = baseEnvironment
        environment.removeValue(forKey: environmentKey)
        if supportsSelection {
            environment[environmentKey] = GuestLocaleCatalog.initialLocale(
                preferredLanguages: preferredLanguages, supportsKorean: supportsKorean
            )
        }
        return Self(environment: environment)
    }
}
